# Generated by Django 4.2.6 on 2023-10-23 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
