# Generated by Django 4.2.6 on 2023-10-13 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_photo_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='title',
            new_name='description',
        ),
    ]
