# Generated by Django 4.2.6 on 2023-10-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_photo_photo_image_alter_photo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/%Y/%m/%d/'),
        ),
    ]
