# Generated by Django 4.2.6 on 2023-10-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(blank=True, max_length=3000, verbose_name='Текст комментария'),
        ),
    ]
