# Generated by Django 4.2.6 on 2023-10-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='lat_coord',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='city',
            name='long_coord',
            field=models.FloatField(default=0.0),
        ),
    ]
