# Generated by Django 4.2.6 on 2023-11-08 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='description',
        ),
    ]
