# Generated by Django 4.2.7 on 2023-11-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_remove_photo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='lat_coord',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='long_coord',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
